name: CICD

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1

      - name: Install
        run: npm install
        working-directory: ./frontend

      # - name: Lint
      #   run: npm run lint

      - name: Build
        run: npm run dev-build
        working-directory: ./frontend
